#!/usr/bin/env python3

"""
This script lists all databases in MongoDB.
"""

import pymongo

def list_databases():
    """
    Function to list all databases in MongoDB.
    """
    # Connect to MongoDB server
    client = pymongo.MongoClient('mongodb://127.0.0.1:27017')

    # Get the list of database names
    database_names = client.list_database_names()

    # Print the list of databases
    for db_name in database_names:
        print(db_name)

if __name__ == "__main__":
    list_databases()
